# Generated by Django 4.0.6 on 2022-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_order_remove_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Posted_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pita',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
